project:
  type: website

website:
  title: "Parlance"
  image: parlance_cover.png
  google-analytics: G-QXGQ6F7NKT
  repo-branch: main
  repo-url: https://github.com/parlance-labs/website
  repo-actions: [edit]
  favicon: b.png
  bread-crumbs: true
  site-url: "https://parlance-labs.com/"
  open-graph: true
  twitter-card:
     creator: "@HamelHusain"
     site: "@HamelHusain"
     card-style: summary_large_image
  page-footer: 
    center:
      - icon: twitter
        href: https://twitter.com/HamelHusain
      - icon: github
        href: https://github.com/hamelsmu
  navbar:
    background: dark
    pinned: true
    collapse: false
    left:
    - text: Resources
      file: education/
    - text: Services
      file: services.qmd
    - text: Team
      file: team.qmd
  sidebar:
    - title: Resources
      pinned: false
      collapse-level: 3
      style: docked
      contents: education/
 



format:
  html:
    reference-location: document
    theme: 
      dark: [solar, custom.scss]
      light: [flatly, custom-light.scss]
    css:
      - styles.css
    toc: true