project:
  type: website

website:
  title: "Parlance"
  image: parlance_cover.png
  google-analytics: G-QXGQ6F7NKT
  repo-branch: main
  repo-url: https://github.com/parlance-labs/website
  repo-actions: [edit]
  favicon: b.png
  bread-crumbs: true
  site-url: "https://parlance-labs.com/"
  open-graph: true
  twitter-card:
     creator: "@HamelHusain"
     site: "@HamelHusain"
     card-style: summary_large_image
  page-footer: 
    center:
      - icon: twitter
        href: https://twitter.com/HamelHusain
      - icon: github
        href: https://github.com/hamelsmu
  navbar:
    background: dark
    pinned: true
    collapse: false
    left:
    - text: Services
      file: services.qmd
    - text: Team
      file: team.qmd
    - text: Education
      file: education/
  sidebar:
    - title: Resources
      pinned: true
      collapse-level: 2
      style: docked
      contents: 
        - education/index.qmd
        # - section: Applied Fine-Tuning
        #   contents: 
        #     - education/fine_tuning_course/workshop_1.qmd
        #     - education/fine_tuning_course/workshop_4.qmd
        - section: Survey Course
          href: education/index.qmd#conference-talks
          contents:
            - section: Evals
              href: education/evals/index.qmd
              contents: 
                - education/evals/allaire.qmd
                - education/evals/ankur.qmd
                - education/evals/schoelkopf.qmd
            - section: RAG
              href: education/rag/index.qmd
              contents: 
                - education/rag/**/*.qmd
            - section: Fine-Tuning
              href: education/fine_tuning/index.qmd
              contents: education/fine_tuning/**/*.qmd
            - section: Applications
              href: education/applications/index.qmd
              contents: education/applications/**/*.qmd
            - section: Prompt Eng
              href: education/prompt_eng/index.qmd
              contents: education/prompt_eng/**/*.qmd


format:
  html:
    reference-location: document
    theme: 
      dark: [solar, custom.scss]
      light: [flatly, custom-light.scss]
    css:
      - styles.css
    toc: true
