project:
  type: website

website:
  title: "Parlance"
  image: cover_2.png
  google-analytics: G-QXGQ6F7NKT
  favicon: b.png
  bread-crumbs: true
  site-url: "https://parlance-labs.com/"
  page-footer: 
    center:
      - icon: twitter
        href: https://twitter.com/HamelHusain
      - icon: github
        href: https://github.com/hamelsmu
  navbar:
    background: dark
    pinned: true
    collapse: false
    left:
    - text: Resources
      file: talks/
    - text: Services
      file: services.qmd
    - text: Team
      file: team.qmd
 



format:
  html:
    reference-location: document
    theme: 
      dark: [solar, custom.scss]
      light: [flatly, custom-light.scss]
    css:
      - styles.css
    toc: true